### ISSUE TITLE
Review EQ7 tweaks

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/library#192]
@tdegeorge didn't get a chance to properly review the final version of https://github.com/TeamBasedInquiryLearning/precalculus/pull/418 before I needed to merge it for the move to this repo.

Here's the preview link: https://40a64bcc.precalculus-beta-20240616.pages.dev/2024/instructor/EQ7 Let us know if things look alright.

**Comment by tdegeorge** [comment]
Looks great! Thanks for adding the preview link. I was having trouble with it before!
