### ISSUE TITLE
EQ2 Checkit overwritten

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#212]
In https://github.com/TeamBasedInquiryLearning/library/pull/194/files#diff-126e73488609e24427fd63f4a2710859ca2e58fa9bafee86b2f29970bbecaa90, it appears that EL7 Checkit files were moved over and renamed EQ2, and the EQ2 ones ended up as EL1.  The rest of the ELs appear to be permuted, but those were all identical anyways.

![image](https://github.com/user-attachments/assets/2937e8cd-f125-49ef-9367-4f81f2209191)

So I think the fix is just rename what's in EL1 to EQ2... PR coming momentarily

**Comment by StevenClontz** [comment]
I caught a few of these - thanks for fixing any I missed

**Comment by siwelwerd** [comment]
I was trying to check off boxes for @AbbyANoble on the tracker, and I swore you had done EQ2 already but I couldn't see it!  Took me a minute to track down what had happened.
