### ISSUE TITLE
MX3 enhancement

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/library#23]
[Activity 4.3.1](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX3.html#activity-131) could follow with an Octave cell reminding students the syntax for matrix multiplication and introducing syntax `inv(A)`. A subsequent activity, which of the following yield the same solution, would fit nicely with `RREF[A|b]` and `inv(A)*b` as correct choices and `RREF[A|I]`, `A*b` as distractors. 

Note that Octave's calculation of `RREF[A|b]` yields $-1.33227e-15$ but `inv(A)*b` yields $0$. It might be good to make a note of this in the book, and then write something about what's going on computationally behind the scenes. I'm not enough of an expert at this to write a coherent paragraph on this.

[Exploration 4.3.10](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX3.html#exploration-49) uses terminology "nonsingular" but I don't think this appears anywhere else in the text.

**Comment by jford1906** [comment]
I added the Octave cell with the syntax. I think the subsequent question suggested is already covered in Activity 4.3.2 and Remark 4.3.3. I can certainly add it if other disagree.
