### ISSUE TITLE
Links to exercise bank in activity book not functioning

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/library#242]
The links to the exercise banks embedded in the activity book are not functional at this time. (tried searching for this issue, but couldn't find it, hope it's not redundant).

**Comment by siwelwerd** [comment]
This is probably related to #224.  A quick check of Calculus shows this is library-wide, not just LA (or Precal).

**Comment by siwelwerd** [comment]
Tagging #224 as library-wide and closing this one as a duplicate.
