### ISSUE TITLE
FN2 Checkit breaks build

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#258]
I see this in the build log being raised from the FN2 checkit:
```
  File "/usr/lib/python3/dist-packages/sage/plot/graphics.py", line 2404, in _matplotlib_tick_formatter
    raise ValueError('Expand the range of the dependent '
ValueError: Expand the range of the dependent variable to allow two multiples of your tick locator (option `ticks`).
```

I'm not sure what this is saying or why it's breaking.  It seems to work when I preview them on my machine.

**Comment by siwelwerd** [comment]
I think this is the location where this is being raised.

https://github.com/TeamBasedInquiryLearning/library/blob/6530d050c6c13ddf6b263f418c50574653aedc5d/source/precalculus/exercises/outcomes/FN/FN2/generator.sage#L113-L119

**Comment by StevenClontz** [comment]
Addressing this now

**Comment by StevenClontz** [comment]
My guess, there's some edge case in seeds 21-999 where the range is only length 1 where this happens. I think that's probably not ideal anyway so I'll see if I can rig the range to be a bit wider.

**Comment by StevenClontz** [comment]
So the special x values are random integers from $\{-8,-7,...,8\}$. I think this bug would trigger possibly when the integers chosen are $\{n,n+1,n+2,n+3\}$, which happens rarely, but maybe happens at least once in the 1000 rolls we generate? We'll see if the full build I triggered for #259 works or not (where I ensure the chosen integers are spaced out a bit more).

**Comment by siwelwerd** [comment]
This made me think it might be nice if I could pass a flag to preview_outcome to try and generate 1000 of an outcome as a final check before I submit a PR to try and catch any edge case that slips through.
