### ISSUE TITLE
Warmup/Cooldown activities

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#28]
This was begun in TeamBasedInquiryLearning/linear-algebra#368.  A 'warmup' activity should function like a mini readiness assurance to reactivate prior knowledge needed that day.  A 'cooldown' is designed for students to do between classes to get them thinking ahead to a key idea in the next section.

**Comment by fragandi** [comment]
Very cool that folks are working on these! I have at least the warmup in all my classes and I would usually just use the first activity of the book.  My cooldowns are really just what I assign for written homework.

I like to call the warmups "Daily Preps" but you could go with the sport analogy and call them "Daily Reps". Is there an idea to do this in Calculus too?

**Comment by siwelwerd** [comment]
To be clear, this one is all @jkostiuk .  If someone wanted to undertake this for the calc book, I suggest creating a separate issue (and maybe a corresponding project) for that.

**Comment by StevenClontz** [comment]
This is done except I think we should rename "cooldown". "Daily Reps", "Practice Activities", etc. might work. @jkostiuk what do you think?

**Comment by jkostiuk** [comment]
How about “Daily Practice”? Sets an expectation that these are meant to be done consistently. On Jul 30, 2024, at 4:06 PM, Steven Clontz ***@***.***> wrote:﻿
This is done except I think we should rename "cooldown". "Daily Reps", "Practice Activities", etc. might work. @jkostiuk what do you think?

**Comment by StevenClontz** [comment]
Nitpicking maybe, but I'm not sure "daily" is quite right upon reflection. "Individual Practice" maybe?
