### ISSUE TITLE
@StevenClontz didn't know if a new issue was needed or a comment here but: given this change to LE3, Activity 1.4.2 should be adjusted to add two rows of zeros to RREF in (c)

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/library#299]
> @StevenClontz didn't know if a new issue was needed or a comment here but: given this change to LE3, Activity 1.4.2 should be adjusted to add two rows of zeros to RREF in (c)

_Originally posted by @jkostiuk in https://github.com/TeamBasedInquiryLearning/library/issues/294#issuecomment-2331820685_

**Comment by jkostiuk** [comment]
circling back on this one, I don't think we need to change 1.4.2? I'm looking at the current instructor version and Activity 1.4.2's reference to 1.3.6 still makes after whatever changes we made?

**Comment by jford1906** [comment]
I agree, I think we can close this
