### ISSUE TITLE
EQ1 Check It Task 2

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#319]
https://library.tbil.org/2024/precalculus/exercises/#/bank/EQ1/1/

Something is going on with Task 2. The answers aren't matching the question. 

See Version 1:
![image](https://github.com/user-attachments/assets/26d2651a-aae6-432d-9a40-28c56e51d0e5)

This one actually has no solution, but it's showing an answer. (As an aside, I think we should make sure none of these have no solution or $(-\infty,\infty)$ as their answers. Or maybe make those a special additional case.)

And I also generated one for an assessment. I closed the CheckIt window before I noticed it was wrong. But here's a screenshot from my pdf. This one should be $(2,\infty)$.

![image](https://github.com/user-attachments/assets/c2aaa898-64ea-4b58-ae55-58b3ecd1e97a)

**Comment by siwelwerd** [comment]
I'm not seeing this in the Preview version and having trouble replicating it locally, so I think it may have been fixed already https://tbil.org/preview/precalculus/exercises/#/bank/EQ1/1/

**Comment by AbbyANoble** [comment]
Preview/PREVIEW strikes again! 🤪

**Comment by siwelwerd** [comment]
>Preview/PREVIEW strikes again! 🤪

See #320
