### ISSUE TITLE
FN5 addition

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#332]
This section could probably use an application example to make sense of why we might compose two functions. Like maybe one function is crop production as a function of {heat, cold, rainfall amount, something?}. And then another that is profit as a function of crop production. We could see why a farmer might want profit as a function of {heat, cold, rainfall amount, something?}.

**Comment by tdegeorge** [comment]
Let me know what you think - I added in an application that I thought would be something the kids would understand more (i.e., more applicable to their own lives).
