### ISSUE TITLE
FN4 typos

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#335]
[Activity 2.4.20](https://library.tbil.org/2024/precalculus/FN4.html#activity-hcompress) , part (a)

Should say consider **an** x-value, not **a**.

And maybe a wording change for "at y=1". That feels like it's referring to a certain spot (and made sense in the previous question where we were looking at x's). Perhaps "Consider an x-value of the two graphs where y=1". Or when? Such that?

The answer choices should refer to **f(2x)** not **2f(x)**.

Tagging @kathypinzon since she was the original author!

**Comment by tdegeorge** [comment]
Spoke to Kathy about the wording and she didn't have a preference. Fixed it to say "Consider an x-value of the two graphs where y=1" and then fixed the other typos.
