### ISSUE TITLE
Terminology in AD

### ISSUE THREAD

**Issue by cg2wilson** [TeamBasedInquiryLearning/library#345]
Need to change several instances of "extrema" to singular "extremum", particularly in AD 4-AD 7

**Comment by cg2wilson** [comment]
Unless people think I'm being overly pedantic?

**Comment by StevenClontz** [comment]
Sounds like a good idea to me.

**Comment by siwelwerd** [comment]
I agree, I don't think that's pedantic at all.  Or maybe I'm equally as pedantic as @cg2wilson :).  But as a general rule, grammatical errors should be fixed and I think this is a grammatical error.

**Comment by jford1906** [comment]
Merged 346, that took care of it
