### ISSUE TITLE
AT6: Adding Activities to Find Bases for Matrix and Polynomial Spaces

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/library#354]
Ever since we compartmentalized the section on abstract vector spaces, I've wanted to restructure some things in AT6 so that my students get practice actually verifying/finding bases for abstract vector spaces. 

We're going to be getting to this unit in a week or two, so I'm going to draft a suggestion quick for your input.

**Comment by StevenClontz** [comment]
Can we rename this and #356 to describe the suggestions?

**Comment by jkostiuk** [comment]
tried these in class today. I was really happy with them--I had a much better conversation about finding these bases than my previous attempts at improvising.

**Comment by StevenClontz** [comment]
Same - Thanks for this work!

I think this is now closable; reopen if I'm overlooking anything.
