### ISSUE TITLE
Label Questions that Assume Calculator Use

### ISSUE THREAD

**Issue by SeppoNiemiColvin** [TeamBasedInquiryLearning/library#37]
I tried to use the CheckItBank to help generate question ideas (even though my department uses a different textbook). Unfortunately one issue I ran into was that some questions occasionally assumed the use of a calculator, and calculators are prohibited for my course. I was often able to simply regenerate when that happened (or look elsewhere for problems), but having something in the problem to flag that would help make sure such a problem doesn't accidentally make its way to students without the technology available to finish it (and help instructors more quickly and easily decide if it is appropriate for their context).

As such having a label or phrase to help mark those questions that assume access to a calculator or other technology would be useful, and one suggestion that was brought up was adding 'using technology if necessary' to the prompt.

**Comment by TienChih** [comment]
This seems like it's already updated.

**Comment by StevenClontz** [comment]
@TienChih if so, please feel free to close (maybe link when/where this happend, if you find the pull request where it happened)

**Comment by TienChih** [comment]
https://github.com/TeamBasedInquiryLearning/calculus/pull/130
