### ISSUE TITLE
Calculus SQ3 Series Definition 

### ISSUE THREAD

**Issue by jbunn3** [TeamBasedInquiryLearning/library#372]
This is something I'm pretty adamant about, so I have to bring this up. In [Definition 8.3.12](https://tbil.org/preview/calculus/SQ3.html#definition-SQ3serieslimit), we define the limit of a series (a number), and then turn around and define an infinite series to be that number. 

I will draft a PR on Monday to clarify the definition of a series as a pair of sequences and create a Remark about common uses (and abuses) of series notation. This change might require some modifications to the rest of the section to improve the flow.

**Comment by StevenClontz** [comment]
Hm - my personal formaliation of a series is that it's a property of a sequence: the limit of its partial sums. I'm interested to see what your approach is.
