### ISSUE TITLE
CheckIt Typo and Suggestion in TI8

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/library#38]
[CheckIt TI8 Problems](https://teambasedinquirylearning.github.io/calculus/2023/exercises/#/bank/TI8/1/) ask if the limit "coverges" instead of "converges"

I wonder if having a preliminary task of "identify if each of these integrals is improper (or not); explain why" would be helpful, like the "identify RREF matrices" before LE2.

**Comment by fragandi** [comment]
I am interested on working on implementing Kate's suggestion, let me know if folks have differing opinions on this!

**Comment by siwelwerd** [comment]
I like @owensks's suggestion and would welcome a PR implementing it.  My only potential concern is that it is adding a task to something that already has four tasks.  It's not immediately clear to me why this one needs four tasks as is though.

**Comment by fragandi** [comment]
What about this structure of question:

You are given integrals A, B, C, D

1. Rewrite each integral as a limit.
2. Which integrals converge? Provide careful evidence for your conclusion.
3. Which integrals diverge? Provide careful evidence for your conclusion.

**Comment by TienChih** [comment]
@fragandi would some of these be proper, so as to capture what @owensks is getting at?

**Comment by fragandi** [comment]
Good point, what about this structure
For each of these integral
1. Decide if proper or improper
2. If improper, rewrite it as a limit and decide if it converge or diverge. 

Q: Do we want the improper integrals to be actually computed or they can use comparison arguments? If the former, we should add something like "compute the integral by finding the antiderivative, using the FTC, and computing the limit."
