### ISSUE TITLE
RAT for Module SQ and Readiness Assurance List

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/library#40]
The [RAT for Module SQ ](RATs/RAT-SQ.tex) contains two problems (5 and 6) which ask students to determine if a given sequence is bounded, increasing, decreasing, but this skill is not listed on the [Readiness Assurance](https://teambasedinquirylearning.github.io/calculus/2023/SQ.html#SQ-readiness) list at the start of the chapter. Meanwhile, "evaluate improper integrals" is listed on the Readiness Assurance list, but the RAT contains no questions affiliated with that topic. I replacing these questions with something along the lines of [Activity 5.8.11](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-352) 
would be a good review before students move toward the Integral Test.

The [Readiness Assurance](https://teambasedinquirylearning.github.io/calculus/2023/SQ.html#SQ-readiness) list of tasks could be updated to include a link back to [Section 5.8: Improper integrals (TI8)](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#TI8) under list item c. Adding to the bulleted list under (a), a link back to [Section 3.9: Limits and Derivatives (AD9)](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#AD9) 
would be appropriate, as well as [Section 1.5: Limits with infinite inputs (LT5)](https://teambasedinquirylearning.github.io/calculus/2023/LT5.html#LT5).

**Comment by fragandi** [comment]
I noticed this too when I used it this term. Will take a crack at it.
TO-DO
- monotone sequence theorem from khan academy
- add improper integral (was very needed!)
- link to limits with infinite inputs

**Comment by fragandi** [comment]
In the RAT I have replaced two of the limit problems with improper integral problems (which are secretly limit problems). Would like to know what folks think of this. 

I would also want to eliminate the reference to l'Hospital as it is not always a topic people cover before series (I cover it when I talk about Taylor series).

**Comment by fragandi** [comment]
PR addressing this issue #451 if it is ok, issue can be closed
