### ISSUE TITLE
PS2 vs PS1 notation for power series

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/library#41]
[Definition 9.1.1](https://teambasedinquirylearning.github.io/calculus/2023/PS1.html#def-PS1powerseries) defines a power series as centered at x=c, where the coefficients are a sequence {a_n}. I guess this makes sense because then the center is x=c, and the coefficients are a numeric sequence {a_n} like we've seen in all the previous sections. I guess "c" stands for _center_.

But then we get to [Remark 9.2.1](https://teambasedinquirylearning.github.io/calculus/2023/PS2.html#remark-51), which then switches what was the center x=c to be the center x=a, and switches the coefficient sequence {a_n} to be a coefficient sequence {c_n}. I guess "c" stands for _coefficient_.

Remark 9.2.1 uses coefficients c_n but then links back to Fact 8.7.1 which uses coefficients a_n. 

Long story short, I think it would probably be good to rewrite this section to agree with coefficients being {a_n} and power series defined by (x-c)^n. Having (x-a)^n with {c_n} sometimes but then (x-c)^n with {a_n} other times is not ideal.

(edit: If y'all agree it is a good idea to switch the centers in PS2 to be consistent with PS1, PS3, and PS4, then I will go through and make the edits and push them)

**Comment by fragandi** [comment]
I am interested in looking this over and closing this, let me know if anyone has updates on their opinions!

**Comment by cg2wilson** [comment]
Addressed in #454
