### ISSUE TITLE
Appendix idea

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#414]
A page with graphs of parent functions (organized by type) would be a helpful reference. (And once it's made, link it to PF1 where I'm referencing it.) Writing this quickly, so I could be missing some, but I'm thinking:

Polynomial
$f(x)=x$
$f(x)=x^2$
$f(x)=x^3$

Other 
$f(x)=|x|$
$f(x)=\sqrt{x}$

Rational
$f(x)=\dfrac{1}{x}$

Exponential and logarithmic
$f(x)=b^x$
$f(x)=\log_b x$
$f(x)=e^x$
$f(x)=\ln x$

Trig
all six trig functions
all six inverse trig functions

**Comment by jbunn3** [comment]
On our Canvas page, we have a list of such graphs. We also included 

$$f(x)=\dfrac{1}{x^2} \text{ and } f(x)=\dfrac{1}{x^3}$$.

We even have the graph of a positive constant hehe. 

Also, we split up the graphs of exponentials for $b>1$ and $0<b<1$.

**Comment by siwelwerd** [comment]
How do we feel about this presentation-wise?  

![image](https://github.com/user-attachments/assets/05314337-4bf2-4b93-803d-f811b4ad855b)
