### ISSUE TITLE
Undo dfracs for exponents and bases of logarithms

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#417]
The very well-intentioned dfrac changeover (#205) went a little too far! See choices A and C of [Activity 5.3.5(a)](https://library.tbil.org/2024/precalculus/EL3.html#act-log-exp-2) (screenshot below) where the exponent overpowers the base!

![image](https://github.com/user-attachments/assets/b5dfcfba-3219-4d2e-9671-33e5569a1093)

Also pops up for the base of logarithms. See choice B of [Activity 5.3.6(b)](https://library.tbil.org/2024/precalculus/EL3.html#act-exp-log-3), (screenshot below)

![image](https://github.com/user-attachments/assets/2cff18e2-5087-4f27-a370-b7b9f03ede21)

Tagging as precalculus, but could potentially be an issue elsewhere!

**Comment by siwelwerd** [comment]
I made a note in the [Style Guide](https://github.com/TeamBasedInquiryLearning/library/wiki/Style-Guide) about this exception to our general preference for `\dfrac`

**Comment by siwelwerd** [comment]
I searched our code for `^{\dfrac` and `_{\dfrac` and fixed all of those instances.  It is possible there are other more complicated exponents or subscripts that don't begin with the `dfrac`, so just reopen this with specifics if we notice any of those.
