### ISSUE TITLE
Upgrade for PreFigure support

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#434]
See https://groups.google.com/g/pretext-announce/c/7zorUaL5MOU/m/IGNZIdTpCgAJ .  The announcement says we need PreTeXt $\geq$ 2.9.2 while we are currently at 2.6.2.

See also #42

**Comment by StevenClontz** [comment]
We're now upgraded; @siwelwerd can close this, or update the issue to be about prefigure implementation.

**Comment by siwelwerd** [comment]
I think we can close this, my initial idea was just to make sure our authors can play around with it and start using it in new projects.
