### ISSUE TITLE
LT1 Check It explanations

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#44]
The explanations are not complete on versions of LT1 where one of the criteria is that the left and right hand limits don't match. 

See https://teambasedinquirylearning.github.io/calculus/2024e/exercises/#/bank/LT1/2/ for example.

**Comment by TienChih** [comment]
Fixed.

**Comment by siwelwerd** [comment]
@TienChih If this is fixed, can we add a reference to the PR that implements the fix?  Then we can close this.

**Comment by TienChih** [comment]
https://github.com/TeamBasedInquiryLearning/library/pull/446
