### ISSUE TITLE
Check-it links are not working in the linear algebra text

### ISSUE THREAD

**Issue by jford1906** [TeamBasedInquiryLearning/library#444]
The links in the text are of the form
https://tbil.org/linear-algebra/2024/exercises/#/bank/LE1/

where they should be 
https://library.tbil.org/2024/linear-algebra/exercises/#/bank/LE1/1/

I'll plan on fixing all of these during the edit-a-thon, but wanted to get an issue going for a reminder

**Comment by StevenClontz** [comment]
My grand plans to work on infrastructure for this project last semester fell flat. I probably will spend Edit-a-thon time working on automating everything a bit better (when I'm not supporting others), which may help here.

**Comment by siwelwerd** [comment]
This is duplicating #224
