### ISSUE TITLE
format command in Octave

### ISSUE THREAD

**Issue by jbunn3** [TeamBasedInquiryLearning/library#477]
I am suggesting that we find a location in the Linear Algebra textbook (maybe LE2 ?) to introduce the format command as an option in Octave. I find that students get a bit frustrated in later sections with messy matrices that don't align well in Octave. Running `format rat`, for example, will align the columns and convert to fractions. Running `format short` uses 5 significant figures but also aligns the columns. But, if there is a better tool, I'm open to it.

**Comment by jbunn3** [comment]
I got my information from [here](uhttps://docs.octave.org/v4.0.1/Terminal-Output.html#:~:text=The%20format%20command%20offers%20some,through%20the%20normal%20echoing%20mechanism.&text=Display%20the%20value%20of%20x%20.&text=Note%20that%20the%20output%20from,formatted%20output%20in%20a%20string.rl)

**Comment by siwelwerd** [comment]
An option might be to pre-load this as input into some of the sage cells to scaffold this.  Syntax is something like this:

```
<sage language="octave">
<input>rref([2,-3,1;3,0,6])</input>
</sage>
```
And here's how that showed up in-text: [Activity 1.2.19](https://library.tbil.org/2024/linear-algebra/LE2.html#LE2-4-19)
