### ISSUE TITLE
PDF Build Broken

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#489]
The PDF build is broken in section LT2 of Calculus

```
! Undefined control sequence.
l.1036 \noindentD
                 . The limit is approximately 0.1667%
```

Guessing this came from #478.

I feel like I remember seeing this kind of error before in the Precal book, but can't remember the exact cause off the top of my head.

**Comment by siwelwerd** [comment]
I think this particular error is caused here.  The `<answer>` is within a `<p>`.  But I think also that the body of the `<activity>` needs to be within a `<statement>` when there is an `<answer>` as well.  I see this kind of thing repeated elsewhere in the file.

https://github.com/TeamBasedInquiryLearning/library/blob/30819300098a864d7fd0617f653548f0a0518cf0/source/calculus/source/01-LT/02.ptx#L15-L91

**Comment by StevenClontz** [comment]
@mlamich1 found this independently and he's working on it now

**Comment by mlamich1** [comment]
I got that <answer> should be out of </statement>. Does this mean <answer> should be out of <activity> as well?

**Comment by siwelwerd** [comment]
No, It should look like
```
<activity>
  <statement>
    statement here
  </statement>
  <answer>
    Answer here
  </answer>
</activity>
```
