### ISSUE TITLE
Correction - Activity 3.6.14

### ISSUE THREAD

**Issue by jehibdon** [TeamBasedInquiryLearning/library#50]
We either need to reword or change the function to the one being doing in Activity 3.6.12.

**Comment by cg2wilson** [comment]
Two things:
1) For the rewording issue, I think that [Activity 3.6.12](https://teambasedinquirylearning.github.io/calculus/2024e/AD6.html#activity-derivative-concavity4) could be resolved by adding either an intermediate task between (c) and (d) which prompts students to think about the connection between the second derivative and increasing/decreasing behavior of the first derivative OR by adding a sentence/follow-up task to (d) prompting them about why we should even think about the first derivative when we're talking about the second derivative. Unless I've misunderstood what the rewording issue is...
2) To address the polynomial example, we could add part (c) to [Activity 3.6.15](https://teambasedinquirylearning.github.io/calculus/2024e/AD6.html#concavity-fluency-checkit) with f(x) = x - cos(pi/2 x) on an interval like [-2pi,2pi]. If the argument of cosine is too much, then this could maybe be made an activity in its own right, and maybe marked as a "challenge"?

**Comment by siwelwerd** [comment]
I think the rewording issue is that 3.6.14 suggests it is using the same function as 3.6.12, but they are different functions. So we should either not refer back to 3.6.12, or make it the same function.

**Comment by siwelwerd** [comment]
> we could add part (c) to [Activity 3.6.15](https://teambasedinquirylearning.github.io/calculus/2024e/AD6.html#concavity-fluency-checkit) with f(x) = x - cos(pi/2 x) on an interval like [-2pi,2pi]. If the argument of cosine is too much, then this could maybe be made an activity in its own right, and maybe marked as a "challenge"?

I like adding it as a part (c), as then an instructor that didn't want to do it could easily skip over it.  We don't have a way to label things as "challenge".  This is maybe not quite at that level, but we do have a way now to add notes to instructors that only show up in the instructor version.
