### ISSUE TITLE
Find/fix PTX:DEPRECATE for misplaced tasks

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/library#510]
https://github.com/TeamBasedInquiryLearning/library/actions/runs/12401969891/job/34622481202?pr=509#step:6:5

**Comment by siwelwerd** [comment]
What's the exact problem here?  Every `<task>` must be in an `<activity>`?

I think xpath can be used to list these pretty easily (assuming the above is correct), as in [this old issue](https://github.com/TeamBasedInquiryLearning/precalculus/issues/192)

**Comment by siwelwerd** [comment]
This should do it: `xpath -e '//task[not(parent::activity)]' source/*/source/*/*.ptx`

**Comment by StevenClontz** [comment]
folding this in to #509

!gif Schitt's Creek fold it in
