### ISSUE TITLE
Missing paragraph tags in remarks

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/library#512]
Finding some spots where remarks didn't include a paragraph tag. They built fine originally, but now as I'm updating things they no longer build.

**Comment by siwelwerd** [comment]
Oof, there are a bunch of these.  I'll work on fixing them all.

For posterity, here is the xpath command I'm using to track all these down:
```
xpath -e '//remark[not(child::p)]' source/precalculus/source/*/*.ptx
```

**Comment by siwelwerd** [comment]
I spotted a few places where some of the text was in a <p> and some was not, which will also not show up correctly.  But the script I put above won't catch that.

**Comment by AbbyANoble** [comment]
> I spotted a few places where some of the text was in a
> 
> and some was not, which will also not show up correctly. But the script I put above won't catch that.

![image](https://github.com/user-attachments/assets/e4169a05-0c31-41f4-984a-1365a4875b04)

**Comment by siwelwerd** [comment]
Okay, this will catch any bare text (i.e. not in a child element like a `<p>`) in a `<remark>`
```
 xpath -e '//remark[text()[normalize-space()]][string-length() > 0]' source/precalculus/source/*/*.ptx
```

**Comment by siwelwerd** [comment]
> Looks like more than just remarks! Here's one in a definition. Didn't check the source, just assuming because the preview is the same!

@StevenClontz Do we know of any other elements that used to show bare text, but now require it to be in a child element? So that I can audit those as well.

**Comment by siwelwerd** [comment]
FWIW there were only three definitions
