### ISSUE TITLE
FN3 Checkit - Learning Outcome description is cutoff

### ISSUE THREAD

**Issue by sharonakrinsky** [TeamBasedInquiryLearning/library#535]
In both the published edition and the preview edition, the description of the learning outcome for FN3 - Characteristics of a Function's Graph reads: **Use the graph of a function to find the domain and range in interval notation, the**

I believe it should be something like **Use the graph of a function to find the domain and range in interval notation, the intercepts, the local and global maxima and minima, and the intervals of increase/decrease for the function.**

**Comment by siwelwerd** [comment]
Clarifying that this in Checkit

**Comment by siwelwerd** [comment]
I believe this is the offending line of source:
https://github.com/TeamBasedInquiryLearning/library/blob/ccecd91a63bad906fa16161e0fd0439d9113df0c/source/precalculus/exercises/bank.xml#L96

I see no reason that shouldn't work, and the fact that it cuts off at the `<m>` makes me suspicious this is a Checkit thing, so assigning to @StevenClontz

**Comment by StevenClontz** [comment]
Descriptions must be plaintext 😢.

**Comment by siwelwerd** [comment]
> Descriptions must be plaintext 😢.

Ahh... looks like a [known issue](https://github.com/StevenClontz/checkit/issues/66)
