### ISSUE TITLE
Broken numbering

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#68]
At least in Calc web-instructor version, it appears numbering has changed so that activities are numbered separately from other things.

**Comment by siwelwerd** [comment]
The targets appear to be missing `<stringparams debug.project.number="the-way-it-should-be"/>`

**Comment by StevenClontz** [comment]
For posterity, as long as `debug.project.number` isn't `no` then we get what we want. But sometimes we like to have a little fun.

**Comment by siwelwerd** [comment]
Accidentally pushed [10dd88d](https://github.com/TeamBasedInquiryLearning/library/commit/10dd88def9fad8251c7e51331068bdbfdddc2f98) to main, which takes care of this.
