### ISSUE TITLE
Update deployment info

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#75]
The [Deploy to the Public](https://github.com/TeamBasedInquiryLearning/library/wiki/Authoring#deploying-to-the-public) info is out of date due to the implementation of Github Actions.

**Comment by StevenClontz** [comment]
> ## Deploying to the public

>
> All changes merged into the main branch are automatically built and deployed to the public at https://tbil.org/ as the "Preview Edition".
