### ISSUE TITLE
Copy Calculus RATS over

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#87]

**Comment by siwelwerd** [comment]
By making the README file, when you navigate to that folder in the repository it will display like this

![image](https://github.com/user-attachments/assets/f26b3e4c-e774-4394-814e-679265380fa1)

**Comment by fragandi** [comment]
In which repo should they live?

**Comment by siwelwerd** [comment]
Here in the library

**Comment by StevenClontz** [comment]
Closed by #137
