### ISSUE TITLE
Migrate issues

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/library#9]
There are a number of outstanding issues in the [Calculus](https://github.com/TeamBasedInquiryLearning/calculus/issues) and [Linear Algebra](https://github.com/TeamBasedInquiryLearning/linear-algebra/issues) repositories that will need to be migrated here.

**Comment by siwelwerd** [comment]
Thinking it will suffice to have labels for the different books, so folks can filter the issues appropriately.

**Comment by StevenClontz** [comment]
You can. I'm planning to put in some hours Sunday to do some preparation. But I'm also thinking that part of the edit a thon can be this sort of house keeping too

**Comment by siwelwerd** [comment]
Okay I'll work on that this afternoon.  Just thinking it will be easier for our contributors to find things to work on if they are all over here, but didn't want to do that prematurely.

**Comment by siwelwerd** [comment]
I have migrated all of the calculus issues.  I was a little more selective with the LA ones, as there are some older ones that I think are probably wontfix at this point.

@StevenClontz please review the remaining issues at https://github.com/TeamBasedInquiryLearning/linear-algebra/issues , and either transfer them yourself or let me know if you want to persist any of those.  Otherwise you can close this, and I'll close out the remaining LA issues as wontfix over there to tidy things up.

**Comment by StevenClontz** [comment]
I'm going to archive both calculus and linear-algebra repos as-is; we can recover and port anything we want down the road, but I think it's safe to move forward here.
